# Generated by Django 5.0.6 on 2025-01-12 06:49

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorEmbeding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='dashboard_app.documentchunk')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='document_embedding_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
