# Generated by Django 5.0.6 on 2025-01-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_documentchunk_content'),
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VectorEmbeding',
            new_name='VectorEmbedding',
        ),
    ]
