# Generated by Django 5.0.6 on 2025-01-12 09:18

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_rename_vectorembeding_vectorembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
